<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cm_ajax_contact_form"
 *
 * Auto generated by Extension Builder 2014-08-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ajax Contact Form',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jannes Dinse, Sebastian Tobies',
	'author_email' => 'jdinse@codemaschine.de, stobies@codemaschine.de',
	'author_company' => 'CODE MASCHINE GmbH, CODE MASCHINE GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
    'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.2',
			'cm_ajax' => '0.5'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
